### ISSUE TITLE
Исправить компиляцию java файлов #4

### ISSUE THREAD

**Issue by qwertas2166** [pfhgil/SungearEngine2D#4]

**Comment by qwertas2166** [comment]
Q:/programs/Java/jdk-17.0.4/bin/javac.exe ./src/*.java -cp Core2D.jar -d "./bin"

**Comment by qwertas2166** [comment]
https://user-images.githubusercontent.com/18326626/197854255-b5aa0848-7180-4565-b679-b125e3bd47ac.png

**Comment by qwertas2166** [comment]
![Image](https://user-images.githubusercontent.com/18326626/197860792-da6501d2-9404-4537-8365-2a5d05ffe202.png)

**Comment by pfhgil** [comment]
Good

**Comment by pfhgil** [comment]
fixed
